silex_blog/src/Entity/Article.php
<?php

namespace Entity;

class Article {
   /**
    * 
    * @var int
    */
    
    private $id;
    
    
    /**
    * 
    * @var string
    */
    
    private $title;
    
    
    /**
    * 
    * @var string
    */
    private $content;
    
    
    /**
    * 
    * @var string
    */
    private $shortContent;
    
    
    /**
    * 
    * @var Category
    */
    private $category;

    public function getId() {
        return $this->id;
    }

    public function getTitle() {
        return $this->title;
    }

    public function getContent() {
        return $this->content;
    }

    public function getShortContent() {
        return $this->shortContent;
        
      
    }

    public function setId($id) {
        $this->id = $id;
        return $this;
    }

    public function setTitle($title) {
        $this->title = $title;
        return $this;
    }

    public function setContent($content) {
        $this->content = $content;
        return $this;
    }

    public function setShortContent($shortContent) {
        $this->shortContent = $shortContent;
        return $this;
    }
    
    public function getCategory() {
        return $this->category;
    }

    public function setCategory(Category $category) {
        $this->category = $category;
        return $this;
    }
    
    /**
     * 
     * @return int|null
     */
    public function getCategoryId() {
        
        if(!is_null($this->category)){
            return $this->category->getId();
        }
        
        return null;
    }
    
    /**
     * 
     * @return string
     */
    public function getCategoryName() {
        
        if(!is_null($this->category)){
            return $this->category->getName();
        }
        
        return '';
    }





}

silex_blog/templates/article_list.html.twig
   {% for article in articles %}
        <h3>{{ article.title }} <small>by {{ article.categoryName }}</small></h3>
        <p><b>{{ article.shortContent }}</b></p>
        <p>{{ article.content }}</p>
        
        {% if not loop.last %}
            <hr>
        {%endif%}
    {% endfor %}

silex_blog/templates/articles.html.twig
{% extends "layout.html.twig" %}

{% block content %}

    <table>
        <tr>
            <th>Id</th>
            <th>Title</th>
            <th>Content</th>
            <th>Short content</th>

        </tr>
        {% for article in articles %}
            <tr>
                <td>{{ article.id }}</td>
                <td>{{ article.title }}</td>
                <td>{{ article.shortContent }}</td>
                <td>{{ article.content }}</td>
                

            </tr>
        {% endfor %}
    </table>
{% endblock %}

silex_blog/templates/categories.html.twig
 <ul class="nav navbar-nav">
    {% for category in categories %}

        <li><a href="{{ path('category', {id: category.id}) }}">{{ category.name }}</a></li>

    {% endfor %}
      
</ul>

silex_blog/templates/category.html.twig
{% extends "layout.html.twig" %}

{% block content %}
    <h2>{{ category.name }}</h2>
    {% include 'article_list.html.twig' %}
{% endblock %}

silex_blog/templates/index.html.twig
{% extends "layout.html.twig" %}

{% block content %}
    Welcome to your new Silex Application!
{% endblock %}

silex_blog/templates/layout.html.twig
<!DOCTYPE html>
<html>
    <head>
 <html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
   
        <title>{% block title '' %} - Blog</title>
     
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link href="{{ asset('css/main.css') }}" rel="stylesheet" type="text/css" /> {# asset est une fonction préinstallée (grace au skeleton)#}

    </head>
    <body>
        {% if user_manager.admin %}
        <nav class="navbar navbar-inverse">
            <div class="container">
                <a class="navbar-brand">Menu admin</a>
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{{ path('admin_categories') }}">Rubriques</a>
                    </li>
                    
                    <li>
                        <a href="{{ path('admin_articles') }}">Articles</a>
                    </li>
                   
                </ul>

            </div>
        </nav>
        {% endif %}
        <nav class="navbar navbar-default">
            <div class="container">
                <a class="navbar-brand" href="{{ path('homepage') }}">Blog</a>
                {# on affiche le rendu de la route categories#}
                {{ render(url('categories')) }}
                
                <ul class="nav navbar-nav navbar-right">
                    {# twig va cherhcer soit 
                        UserManager::getUserconnected()
                        UserManager::hasUserconnected()
                        UserManager::isUserconnected()#}
                    {% if user_manager.userConnected %}
                    
                    
                    <li><a>{{ user_manager.username }}</a></li>
                    
                    
                    <li><a href="{{ path('logout') }}">Déconnexion</a></li> 
                    
                    {% else %}
                    <li><a href="{{ path('register') }}">Créer un compte</a></li>
                    <li><a href="{{ path('login') }}">Connexion</a></li> 
                    
                    {% endif %}
                </ul>

            </div>
        </nav>
        <div class="container">
            {% for label, flashes in global.session.flashbag.all %} {# correspond à foreach as label => flashes #}
                {% for flash in flashes %}
                    {% if label == 'error' %}
                        {%set label = 'danger' %}
                    {% endif %}
                        <div class="alert alert-{{ label}}">{{ flash|raw }}</div>
                {% endfor %}
            {% endfor %}
            {% block content %}{% endblock %}
        </div>
        
        {% block javascripts %}
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        {% endblock %}

    </body>
</html>

silex_blog/templates/login.html.twig
{% extends "layout.html.twig" %}

{% block content %}
    <h1>Connexion</h1>
    <form method="post">
         <div class ="form-group">
            <label class="control-label">Email</label>
            <input type="text" name="email" value="{{ email }}"class="form-control">
        </div>
        
         <div class ="form-group">
            <label class="control-label">Mot de passe</label>
            <input type="password" name="password" class="form-control">
        </div>
       
        <div>
            <button type="submit" class="btn btn-primary">Connexion</button>
    </form>
  
{% endblock %}

silex_blog/templates/register.html.twig
{% extends "layout.html.twig" %}

{% block content %}
    <h2>Inscription</h2>
    <form method="post">
        <div class ="form-group">
            <label class="control-label">Nom</label>
            <input type="text" name="lastname" class="form-control">
        </div>
        
         <div class ="form-group">
            <label class="control-label">Prénom</label>
            <input type="text" name="firstname" class="form-control">
        </div>
        
         <div class ="form-group">
            <label class="control-label">Email</label>
            <input type="text" name="email" class="form-control">
        </div>
        
         <div class ="form-group">
            <label class="control-label">Mot de passe</label>
            <input type="password" name="password" class="form-control">
        </div>
       
        <div>
            <button type="submit" class="btn btn-primary">Enregistrer</button>
        </div>
    </form>
{% endblock %}